User.create!([
  {email: "pkemble@gmail.com", encrypted_password: "$2a$12$41A4v/sDfuXSK4xj15jaEOqNvXOPhSnTODSlHKpIh9inIT8cEAPuy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, encrypted_otp_secret: "XHLOTAJNJQH55JCLHHRKFNSY", encrypted_otp_secret_iv: nil, encrypted_otp_secret_salt: nil, consumed_timestep: nil, otp_required_for_login: nil, otp_secret: nil}
])
Post.create!([
  {title: "florida1", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "detonatation I", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "on the sybian", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "happiest times", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "what kind of friends are they supposed to be?", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "taking care not to care", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "i'm too loud for my downstairs neighbors", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "austin, texas day 1", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "new year's eve", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "girls and boys", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "an isolationist", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "21jun07 People's Republic", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "19jun07 PJ Ryans", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "27may07 PJ Ryans", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "continuum in cataclysmic confusion", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "women", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "the heard world is...", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "public pees", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "my epitaph", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "high power luncheon", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "the heard world companion: an introduction", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "", user_id: 1, enclosure: nil, wpid: nil, notebook_id: nil},
  {title: "the heard world summer vacation special 01", user_id: 1, enclosure: "http://petekemble.com/heardworld/9a.mp3", wpid: 35, notebook_id: nil},
  {title: "the heard world summer vacation special 02", user_id: 1, enclosure: "http://petekemble.com/heardworld/9b.mp3", wpid: 34, notebook_id: nil},
  {title: "the heard world summer vacation special 03", user_id: 1, enclosure: "http://petekemble.com/heardworld/9c.mp3", wpid: 33, notebook_id: nil},
  {title: "the heard world summer vacation special 04", user_id: 1, enclosure: "http://petekemble.com/heardworld/9d.mp3", wpid: 32, notebook_id: nil},
  {title: "the heard world 21", user_id: 1, enclosure: "http://petekemble.com/heardworld/21.mp3", wpid: 31, notebook_id: nil},
  {title: "the heard world 22", user_id: 1, enclosure: "http://petekemble.com/heardworld/22.mp3", wpid: 30, notebook_id: nil},
  {title: "the heard world lo-fi extravaganza", user_id: 1, enclosure: "http://petekemble.com/heardworld/poocast1.mp3", wpid: 29, notebook_id: nil},
  {title: "the heard world 23", user_id: 1, enclosure: "http://petekemble.com/heardworld/23.mp3", wpid: 28, notebook_id: nil},
  {title: "the heard world degeneration special", user_id: 1, enclosure: "http://petekemble.com/heardworld/24.mp3", wpid: 27, notebook_id: nil},
  {title: "the heard world 26", user_id: 1, enclosure: "http://petekemble.com/heardworld/26.mp3", wpid: 25, notebook_id: nil},
  {title: "the heard world degeneration plateau", user_id: 1, enclosure: "http://petekemble.com/heardworld/25.mp3", wpid: 26, notebook_id: nil},
  {title: "the heard world 28", user_id: 1, enclosure: "http://petekemble.com/heardworld/28.mp3", wpid: 23, notebook_id: nil},
  {title: "the heard world 27 - circuit bending!", user_id: 1, enclosure: "http://petekemble.com/heardworld/27.mp3", wpid: 24, notebook_id: nil},
  {title: "the piezo electric world 29", user_id: 1, enclosure: "http://petekemble.com/heardworld/29.mp3", wpid: 22, notebook_id: nil},
  {title: "the heard world 32: a collection of distorted noises", user_id: 1, enclosure: "http://www.petekemble.com/images/IMGP1536.AVI\n4848056\nvideo/x-msvideo\n", wpid: 40, notebook_id: nil},
  {title: "the glamorous life of circuit bending", user_id: 1, enclosure: "http://petekemble.com/heardworld/30.mp3", wpid: 21, notebook_id: nil},
  {title: "the heard world 31: a collection of noises", user_id: 1, enclosure: "http://petekemble.com/heardworld/31.mp3", wpid: 39, notebook_id: nil},
  {title: "the heard world (weekend special) 18", user_id: 1, enclosure: "http://petekemble.com/heardworld/18.mp3", wpid: 37, notebook_id: nil},
  {title: "the heard world 33: a very tonal affair", user_id: 1, enclosure: "http://petekemble.com/heardworld/33.mp3", wpid: 41, notebook_id: nil},
  {title: "the heard world 34", user_id: 1, enclosure: "http://petekemble.com/heardworld/34.mp3", wpid: 42, notebook_id: nil},
  {title: "the heard world 35: a depressing conversation", user_id: 1, enclosure: "http://petekemble.com/heardworld/35.mp3", wpid: 43, notebook_id: nil},
  {title: "the heard world 36: FM Radio and misogyny", user_id: 1, enclosure: "http://petekemble.com/heardworld/36.mp3", wpid: 44, notebook_id: nil},
  {title: "the heard world 37: aleatory and creatures", user_id: 1, enclosure: "http://petekemble.com/heardworld/37.mp3", wpid: 45, notebook_id: nil},
  {title: "the heard world 38: FM Radio", user_id: 1, enclosure: "http://petekemble.com/heardworld/38.mp3", wpid: 46, notebook_id: nil},
  {title: "the heard world 39: Degeneration Special II", user_id: 1, enclosure: "http://petekemble.com/heardworld/39.mp3", wpid: 47, notebook_id: nil},
  {title: "the heard world 40: drones", user_id: 1, enclosure: "http://petekemble.com/heardworld/40a.mp3", wpid: 49, notebook_id: nil},
  {title: "the heard world 41: drones; exposition", user_id: 1, enclosure: "http://petekemble.com/heardworld/41.mp3", wpid: 50, notebook_id: nil},
  {title: "the heard world 42: anniversary special", user_id: 1, enclosure: "http://petekemble.com/heardworld/42.mp3", wpid: 51, notebook_id: nil},
  {title: "the heard world 43: Europe", user_id: 1, enclosure: "http://petekemble.com/heardworld/43.mp3", wpid: 52, notebook_id: nil},
  {title: "the heard world 44: wallowing", user_id: 1, enclosure: "http://petekemble.com/heardworld/44a.mp3", wpid: 53, notebook_id: nil},
  {title: "the heard world 45: lecture - citizenship", user_id: 1, enclosure: "http://petekemble.com/heardworld/45.mp3", wpid: 54, notebook_id: nil},
  {title: "the heard world 46: Dallas", user_id: 1, enclosure: "http://petekemble.com/heardworld/46.mp3", wpid: 55, notebook_id: nil},
  {title: "the heard world 47: bedroom band days", user_id: 1, enclosure: "http://petekemble.com/heardworld/47.mp3", wpid: 56, notebook_id: nil},
  {title: "the heard world 48: dutch heartbreak", user_id: 1, enclosure: "http://petekemble.com/heardworld/48.mp3", wpid: 57, notebook_id: nil},
  {title: "the heard world 49: b-sides to songs you'll never hear", user_id: 1, enclosure: "http://petekemble.com/heardworld/49a.mp3", wpid: 58, notebook_id: nil},
  {title: "the heard world 50: an anxious goodbye", user_id: 1, enclosure: "1567306599:1", wpid: 60, notebook_id: nil},
  {title: "mississippi 2021", user_id: 4, enclosure: nil, wpid: nil, notebook_id: 1},
  {title: "", user_id: 4, enclosure: nil, wpid: nil, notebook_id: nil}
])
Notebook.create!([
  {title: "a marble notebook", description: "bitter stuff"},
  {title: "the heard world podcast", description: "oh, you know"},
  {title: "the ascii fish", description: "the old boycrikey blogger"},
  {title: "dummy 4", description: "description dummy 4"}
])
ActionText::RichText.create!([
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 377},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 254},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 255},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 256},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 257},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 258},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 259},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 260},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 261},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 262},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 263},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 264},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 265},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 266},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 267},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 268},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 269},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 270},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 271},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 272},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 273},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 274},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 275},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 276},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 277},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 278},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 279},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 280},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 281},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 282},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 283},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 284},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 285},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 286},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 287},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 288},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 289},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 290},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 291},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 292},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 293},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 294},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 295},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 340},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 341},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 342},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 343},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 344},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 345},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 346},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 347},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 348},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 349},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 350},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 351},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 352},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 353},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 354},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 355},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 356},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 357},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 358},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 359},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 360},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 361},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 362},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 363},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 364},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 365},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 366},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 367},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 368},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 369},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 370},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 371},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 372},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 373},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 374},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 375},
  {name: "content", body: #<ActionText::Content "<div class=\"trix-conte...">, record_type: "Post", record_id: 376}
])
